### ISSUE TITLE
Invalid cookie data

### ISSUE THREAD

**Issue by roughnecks** [jshackles/idle_master_py#16]
Hi there,
I used Idle Master py for quite a long time, always had the same setup/settings, but since the latest Steam client update (not sure if a coincidence) I cannot login anymore: Invalid cookie data is the error message I get.

I use cookies from Google Chrome and I tried countless time to set up the settings file, without success. I also noticed that every time I close and re-open my browser, the "sessionid" and "steamparental" cookies have different content.. don't know if that is standard behaviour or not.

Is there anything else I can try?
Thanks

**Comment by jshackles** [comment]
Did you update your script (or binaries) with the new ones released 9 days ago?  Valve made a change in the badges page and the program was updated to reflect these changes.

**Comment by roughnecks** [comment]
I updated it several days ago, not sure when because I decided to Idle those games on Windows, when I saw the failures and then I didn't check for updates anymore.

I'll try now, even if I have no more games to idle and report back. Thanks

**Comment by roughnecks** [comment]
Downloaded "start.py" and it's working again, thanks for helping me out. :+1:
